theme: jekyll-theme-cayman
title: The Proteus Institute
description: Dedicated to facilitating the creation of bio-inspired AI.
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - index.md
